### ISSUE TITLE
Android 13

### ISSUE THREAD

**Issue by Metalomeus** [Waterdish/zelda3-android#1] opened 2023-08-21 10:55 UTC
It doesn't start the game.....goes back to launcher....redmi note 9 pro android 13

**Comment by Waterdish** [comment] 2023-08-21 16:27
Just to check, since that is the same thing that happens when the assets aren't in the folder, is your zelda3_assets.dat 668kb and in the same folder as the generated zelda3.ini?

**Comment by Metalomeus** [comment] 2023-08-21 16:31
![Screenshot_20230821-182930](https://github.com/Waterdish/zelda3-android/assets/71162300/306a8405-c3de-4380-9221-13a323e25010)
Thanks for answering....
The filesize is 668kb. It creates the folders also the first time.....

**Comment by Waterdish** [comment] 2023-08-21 17:42
Yup looks normal to me. I'll use an android 13 emulator to see what might be the issue.

**Comment by Metalomeus** [comment] 2023-08-21 17:53
Thanks for your efforts....I patiently wait for an update if there's any 🙂

**Comment by Waterdish** [comment] 2023-08-21 23:48
I am able to run it in android studio using an android 13 emulator. Are the files on your main phone storage or an sd card?
Also try changing the renderer to SDL-Software in zelda3.ini.

**Comment by zax304** [comment] 2023-08-22 08:13
I'm having the same problem how do I change the renderer to sdl software

**Comment by Metalomeus** [comment] 2023-08-22 08:30
I tried all 4 rendering methods but none worked for me... Look into zelda.ini in /sdcard/Android/data/com.dishii.zelda3/files

**Comment by zax304** [comment] 2023-08-22 14:11
None of the renderings work

**Comment by Waterdish** [comment] 2023-08-22 19:50
So I'm quite certain it's due to some storage permission problem, but Im not running into the issue using the emulator built into android studio. I'll try out a different emulator like nox and see if I can reproduce it there. 
I want to confirm, are the files being placed in your internal storage or an external microsd card? I have been using internal storage for all my tests.

**Comment by Waterdish** [comment] 2023-08-23 02:12
https://github.com/Waterdish/zelda3-android/releases/tag/v1.0.2
Try this release. It asks for full external file permissions which I hope solves the issue. If it's not that, then I apologize but I'm not sure what else could be the problem. Make sure you switch the renderer back to SDL if you haven't already.

**Comment by zax304** [comment] 2023-08-23 08:21
I just compiled on my laptop again I can confirm it works

**Comment by Waterdish** [comment] 2023-08-23 16:27
Awesome thank you for confirming. I'll close the issue now.

**Closed as completed by Waterdish** 2023-08-23 16:27 UTC
